### ISSUE TITLE
FPC and Lazarus packages for Haiku

### ISSUE THREAD

**Issue by Alexey-T** [s40in/HakiDecors#6]
@s40in 
Thanks for packages! could you update them - they are year old. and FPC package

a) it don't add "fpc" to PATH so Laz cannot find it
b) it don't create fpc.cfg- so Laz cannot use it (after I set path by hands)

**Comment by s40in** [comment]
HakiDecors updated on my repo http://repo.hakilo.ru/x86_64/ (64bit only). 

I do not plan to upgrade freepascal and lazarus packages yet
